[[targets]]
  hosts = ['8.8.8.8', '8.8.4.4']
  [targets.tags]
     country = 'fr'
     server = 'french'

[[targets]]
  hosts = ['google.fr']
  [targets.tags]
     country = 'fr'
     server = 'french'

[[targets]]
  hosts = ['amazon.es']
  [targets.tags]
     country = 'es'
     server = 'spain'

[[targets]]
  hosts = ['facebook.de']
  [targets.tags]
     country = 'de'
     server = 'germany'
